[repository]
name = "hyprsubs"
authors = ["0TrashPanda"]
commit_pins = []

[hyprsubs]
description = "2D workspaces: groups (horizontal) with subs (vertical) and 1:1 trackpad swiping on both axes"
authors = ["0TrashPanda"]
output = "hyprsubs.so"
build = ["make all"]
